CREATE TABLE IF NOT EXISTS mate_memory_write_ledger (
    id                      BIGINT       NOT NULL PRIMARY KEY,
    workspace_id            BIGINT       NOT NULL,
    agent_id                BIGINT       NOT NULL,
    owner_key               VARCHAR(128),
    memory_type             VARCHAR(32)  NOT NULL,
    memory_key              VARCHAR(256) NOT NULL,
    source                  VARCHAR(64)  NOT NULL,
    source_conversation_id  VARCHAR(256),
    source_ref              VARCHAR(1000),
    content_hash            VARCHAR(64)  NOT NULL,
    content                 MEDIUMTEXT,
    token_estimate          INT          NOT NULL DEFAULT 0,
    version_no              INT          NOT NULL DEFAULT 1,
    supersedes_id           BIGINT,
    status                  VARCHAR(32)  NOT NULL,
    rejection_reason        VARCHAR(1000),
    resolved_by             VARCHAR(128),
    resolved_at             DATETIME,
    create_time             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted                 INT          NOT NULL DEFAULT 0,
    KEY idx_memory_ledger_scope_key (workspace_id, agent_id, owner_key, memory_type, memory_key, create_time),
    KEY idx_memory_ledger_status_time (workspace_id, status, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Long-term memory write decisions and conflict versions';
