package vip.mate.skill.proposal;

/** Untrusted candidate generated by reflection or routine mining. */
public record SkillProposalDraft(
        Long workspaceId,
        Long agentId,
        String sourceType,
        String sourceConversationId,
        Long sourceRunId,
        String action,
        String skillName,
        String content,
        String oldText,
        String newText,
        String evidenceJson
) {
}
