CREATE TABLE IF NOT EXISTS mate_skill_change_proposal (
    id                      BIGINT       NOT NULL PRIMARY KEY,
    workspace_id            BIGINT       NOT NULL,
    proposal_hash           VARCHAR(64)  NOT NULL,
    agent_id                BIGINT,
    source_type             VARCHAR(32)  NOT NULL,
    source_conversation_id  VARCHAR(256),
    source_run_id           BIGINT,
    action                  VARCHAR(16)  NOT NULL,
    skill_name              VARCHAR(128) NOT NULL,
    before_content          MEDIUMTEXT,
    after_content           MEDIUMTEXT,
    diff_text               MEDIUMTEXT,
    evidence_json           MEDIUMTEXT,
    risk_level              VARCHAR(16)  NOT NULL DEFAULT 'MEDIUM',
    status                  VARCHAR(24)  NOT NULL DEFAULT 'PENDING',
    reviewer                VARCHAR(128),
    review_note             VARCHAR(1000),
    snapshot_id             BIGINT,
    applied_skill_id        BIGINT,
    applied_version         VARCHAR(64),
    rollback_status         VARCHAR(24),
    reviewed_at             DATETIME,
    applied_at              DATETIME,
    rolled_back_at          DATETIME,
    create_time             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted                 INT          NOT NULL DEFAULT 0,
    UNIQUE KEY uk_skill_proposal_hash (workspace_id, proposal_hash, deleted),
    KEY idx_skill_proposal_status_time (workspace_id, status, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Human-reviewed autonomous skill changes';
