-- Persistent, replay-oriented acquisition ledger for structured AI-news sources.
CREATE TABLE mate_ai_news_source_endpoint (
    id BIGINT NOT NULL PRIMARY KEY,
    endpoint_key VARCHAR(160) NOT NULL,
    catalog_version INT NOT NULL DEFAULT 0,
    source_key VARCHAR(128) NULL,
    provider_id VARCHAR(64) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    adapter VARCHAR(32) NOT NULL,
    endpoint_url VARCHAR(4096) NOT NULL,
    endpoint_url_hash VARCHAR(64) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    languages_json TEXT NULL,
    categories_json TEXT NULL,
    poll_interval_seconds INT NOT NULL DEFAULT 900,
    evidence_eligible BOOLEAN NOT NULL DEFAULT FALSE,
    rights_status VARCHAR(64) NOT NULL DEFAULT 'operator_managed',
    raw_retention VARCHAR(32) NOT NULL DEFAULT 'metadata_only',
    robots_status VARCHAR(64) NOT NULL DEFAULT 'operator_managed',
    etag VARCHAR(1024) NULL,
    last_modified VARCHAR(1024) NULL,
    last_attempt_at DATETIME(3) NULL,
    last_success_at DATETIME(3) NULL,
    next_poll_at DATETIME(3) NULL,
    consecutive_failures INT NOT NULL DEFAULT 0,
    last_http_status INT NULL,
    last_error VARCHAR(2000) NULL,
    config_fingerprint VARCHAR(64) NOT NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted INT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_ai_news_source_endpoint_key (endpoint_key),
    INDEX idx_ai_news_source_endpoint_due (enabled, next_poll_at),
    INDEX idx_ai_news_source_endpoint_url (provider_id, endpoint_url_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE mate_ai_news_ingestion_run (
    id BIGINT NOT NULL PRIMARY KEY,
    endpoint_id BIGINT NOT NULL,
    provider_id VARCHAR(64) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    trigger_type VARCHAR(32) NOT NULL,
    trace_id VARCHAR(64) NULL,
    started_at DATETIME(3) NOT NULL,
    finished_at DATETIME(3) NULL,
    run_status VARCHAR(32) NOT NULL DEFAULT 'started',
    http_status INT NULL,
    not_modified BOOLEAN NOT NULL DEFAULT FALSE,
    transport_count INT NOT NULL DEFAULT 0,
    item_count INT NOT NULL DEFAULT 0,
    new_item_count INT NOT NULL DEFAULT 0,
    new_version_count INT NOT NULL DEFAULT 0,
    unchanged_item_count INT NOT NULL DEFAULT 0,
    bytes_received BIGINT NOT NULL DEFAULT 0,
    retry_count INT NOT NULL DEFAULT 0,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(2000) NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted INT NOT NULL DEFAULT 0,
    INDEX idx_ai_news_ingestion_run_endpoint (endpoint_id, started_at),
    INDEX idx_ai_news_ingestion_run_status (run_status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE mate_ai_news_source_item (
    id BIGINT NOT NULL PRIMARY KEY,
    endpoint_id BIGINT NOT NULL,
    identity_hash VARCHAR(64) NOT NULL,
    external_item_id VARCHAR(1024) NULL,
    canonical_url VARCHAR(4096) NULL,
    canonical_url_hash VARCHAR(64) NULL,
    source_url VARCHAR(4096) NOT NULL,
    source_tier VARCHAR(16) NOT NULL DEFAULT 'community',
    first_observed_at DATETIME(3) NOT NULL,
    last_observed_at DATETIME(3) NOT NULL,
    latest_version_id BIGINT NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted INT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_ai_news_source_item_identity (endpoint_id, identity_hash),
    INDEX idx_ai_news_source_item_canonical (canonical_url_hash),
    INDEX idx_ai_news_source_item_seen (endpoint_id, last_observed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE mate_ai_news_source_item_version (
    id BIGINT NOT NULL PRIMARY KEY,
    source_item_id BIGINT NOT NULL,
    ingestion_run_id BIGINT NOT NULL,
    version_hash VARCHAR(64) NOT NULL,
    title VARCHAR(512) NULL,
    snippet MEDIUMTEXT NULL,
    content MEDIUMTEXT NULL,
    source_published_at DATETIME(3) NULL,
    published_at_raw VARCHAR(512) NULL,
    source_modified_at DATETIME(3) NULL,
    modified_at_raw VARCHAR(512) NULL,
    language VARCHAR(32) NULL,
    provenance_json MEDIUMTEXT NOT NULL,
    observed_at DATETIME(3) NOT NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted INT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_ai_news_source_item_version (source_item_id, version_hash),
    INDEX idx_ai_news_source_item_version_run (ingestion_run_id),
    INDEX idx_ai_news_source_item_version_published (source_published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE mate_ai_news_ingestion_run_item (
    id BIGINT NOT NULL PRIMARY KEY,
    ingestion_run_id BIGINT NOT NULL,
    source_item_id BIGINT NOT NULL,
    source_item_version_id BIGINT NOT NULL,
    observation_outcome VARCHAR(32) NOT NULL,
    observed_at DATETIME(3) NOT NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted INT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_ai_news_ingestion_run_item (ingestion_run_id, source_item_id),
    INDEX idx_ai_news_ingestion_run_item_version (source_item_version_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE mate_ai_news_raw_capture (
    id BIGINT NOT NULL PRIMARY KEY,
    ingestion_run_id BIGINT NOT NULL,
    endpoint_id BIGINT NOT NULL,
    request_url VARCHAR(4096) NOT NULL,
    request_url_hash VARCHAR(64) NOT NULL,
    attempt_no INT NOT NULL DEFAULT 1,
    final_url VARCHAR(4096) NULL,
    http_status INT NULL,
    content_type VARCHAR(256) NULL,
    etag VARCHAR(1024) NULL,
    last_modified VARCHAR(1024) NULL,
    retry_after VARCHAR(512) NULL,
    declared_content_length BIGINT NULL,
    received_bytes BIGINT NOT NULL DEFAULT 0,
    representation_digest VARCHAR(64) NULL,
    retention_applied VARCHAR(32) NOT NULL,
    body_object_key VARCHAR(1024) NULL,
    raw_body MEDIUMBLOB NULL,
    truncated BOOLEAN NOT NULL DEFAULT FALSE,
    not_modified BOOLEAN NOT NULL DEFAULT FALSE,
    started_at DATETIME(3) NOT NULL,
    finished_at DATETIME(3) NOT NULL,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(2000) NULL,
    revalidated_from_capture_id BIGINT NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted INT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_ai_news_raw_capture_run_url (ingestion_run_id, request_url_hash, attempt_no),
    INDEX idx_ai_news_raw_capture_resource (endpoint_id, request_url_hash, finished_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
