-- Content-addressed, replayable snapshots for every AI-news discovery run.
CREATE TABLE mate_ai_news_discovery_run (
    id BIGINT NOT NULL PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    topic VARCHAR(1000) NOT NULL,
    window_start DATETIME(3) NOT NULL,
    window_end DATETIME(3) NOT NULL,
    observed_at DATETIME(3) NOT NULL,
    requested_max_candidates INT NOT NULL,
    query_count INT NOT NULL,
    cached_query_count INT NOT NULL DEFAULT 0,
    successful_query_count INT NOT NULL DEFAULT 0,
    unique_url_count INT NOT NULL DEFAULT 0,
    selected_candidate_count INT NOT NULL DEFAULT 0,
    structured_source_count INT NOT NULL DEFAULT 0,
    ranking_policy_version VARCHAR(128) NOT NULL,
    snapshot_hash VARCHAR(64) NOT NULL,
    ranking_hash VARCHAR(64) NOT NULL,
    snapshot_json MEDIUMTEXT NOT NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted INT NOT NULL DEFAULT 0,
    INDEX idx_ai_news_discovery_run_workspace (workspace_id, observed_at),
    INDEX idx_ai_news_discovery_run_window (window_start, window_end, ranking_policy_version),
    INDEX idx_ai_news_discovery_run_snapshot (snapshot_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
